// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgqidnjzrdigxcdnjqge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJncWlkbmp6cmRpZ3hjZG5qcWdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDM4OTIsImV4cCI6MjA2ODkxOTg5Mn0.zVPW7KkclWKHCqgwo9PvBHadTo3YVGuSfNYraVBewNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});